name: 'Build Native Module'
description: 'Sets up environment, builds the native module using napi-rs, and uploads the artifact.'
inputs:
  name:
    description: 'Platform identifier (e.g., linux-x64-gnu)'
    required: true
  os:
    description: 'Runner OS (e.g., ubuntu-latest)'
    required: true
  target:
    description: 'Rust target triple (e.g., x86_64-unknown-linux-gnu)'
    required: true
  artifact-name-prefix:
    description: 'Prefix for the artifact name'
    required: false
    default: 'pr-binaries'
  arch:
    description: 'Architecture (e.g., x64, arm64)'
    required: true

runs:
  using: "composite"
  steps:
    - name: å®Ÿè¡Œæƒ…å ±ã®åˆæœŸåŒ–
      shell: bash
      run: |
        echo "ACTION_SUMMARY=[]" >> $GITHUB_ENV
        echo "ARTIFACTS_INFO=[]" >> $GITHUB_ENV

    - name: Rustãƒ„ãƒ¼ãƒ«ãƒã‚§ã‚¤ãƒ³ã®ã‚»ãƒƒãƒˆã‚¢ãƒƒãƒ—
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        targets: ${{ inputs.target }}

    - name: Rustã‚¿ãƒ¼ã‚²ãƒƒãƒˆã®è¿½åŠ 
      shell: bash
      run: |
        rustup target add ${{ inputs.target }}
        echo "ACTION_SUMMARY=$(echo $ACTION_SUMMARY | jq -c '. += ["Rustã‚¿ãƒ¼ã‚²ãƒƒãƒˆ '${{ inputs.target }}' ã‚’è¿½åŠ ã—ã¾ã—ãŸ"]')" >> $GITHUB_ENV

    - name: Node.jsè¨­å®š
      uses: ./.github/actions/node-setup
      with:
        node-version: '' # Use project's default
        package-path: '.'

    - name: Linux ä¾å­˜é–¢ä¿‚ã®ã‚¤ãƒ³ã‚¹ãƒˆãƒ¼ãƒ«ã¨è¨­å®š
      if: startsWith(inputs.os, 'ubuntu')
      shell: bash
      run: |
        sudo apt-get update -y
        if [[ "${{ inputs.target }}" == "x86_64-unknown-linux-gnu" ]]; then
          echo "Installing dependencies for x86_64 native compilation..."
          sudo apt-get install -y --no-install-recommends \
            pkg-config \
            libx11-dev \
            libxtst-dev \
            libdbus-1-dev # electron-rs/cargo-build requires this
          echo "ACTION_SUMMARY=$(echo $ACTION_SUMMARY | jq -c '. += ["Linuxä¾å­˜é–¢ä¿‚ã‚’ã‚¤ãƒ³ã‚¹ãƒˆãƒ¼ãƒ«ã—ã¾ã—ãŸ (x86_64)"]')" >> $GITHUB_ENV
        fi

    - name: ãƒã‚¤ãƒŠãƒªãƒ“ãƒ«ãƒ‰ (napi build)
      shell: bash
      run: |
        set -ex
        echo "Running napi build for target: ${{ inputs.target }}"
        if [[ "${{ inputs.os }}" == "macos-latest" && "${{ inputs.target }}" == "x86_64-apple-darwin" && "$(uname -m)" == "arm64" ]]; then
          echo "Setting up cross-compilation from ARM64 to x86_64 on macOS..."
          export CARGO_TARGET_X86_64_APPLE_DARWIN_LINKER="$(xcrun --find clang)"
          export SDKROOT=$(xcrun --sdk macosx --show-sdk-path)
          export MACOSX_DEPLOYMENT_TARGET=$(xcrun --sdk macosx --show-sdk-platform-version)
          echo "ACTION_SUMMARY=$(echo $ACTION_SUMMARY | jq -c '. += ["macOSã§ARM64ã‹ã‚‰x86_64ã¸ã®ã‚¯ãƒ­ã‚¹ã‚³ãƒ³ãƒ‘ã‚¤ãƒ«ã‚’è¨­å®šã—ã¾ã—ãŸ"]')" >> $GITHUB_ENV
        fi
        
        pnpm exec napi build --platform --release --target ${{ inputs.target }}
        echo "ACTION_SUMMARY=$(echo $ACTION_SUMMARY | jq -c '. += ["ã‚¿ãƒ¼ã‚²ãƒƒãƒˆ '${{ inputs.target }}' ç”¨ã®ãƒã‚¤ãƒ†ã‚£ãƒ–ãƒ¢ã‚¸ãƒ¥ãƒ¼ãƒ«ã‚’ãƒ“ãƒ«ãƒ‰ã—ã¾ã—ãŸ"]')" >> $GITHUB_ENV

    - name: List built files
      shell: bash
      run: |
        NODE_FILES=$(ls -la *.node)
        echo "BUILT_FILES<<EOF" >> $GITHUB_ENV
        echo "$NODE_FILES" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: æˆæžœç‰©ã‚’ã‚¢ãƒƒãƒ—ãƒ­ãƒ¼ãƒ‰
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name-prefix }}-${{ inputs.name }}
        path: "*.node"
      
    - name: æˆæžœç‰©æƒ…å ±ã®è¨˜éŒ²
      shell: bash
      run: |
        ARTIFACT_NAME="${{ inputs.artifact-name-prefix }}-${{ inputs.name }}"
        echo "ARTIFACTS_INFO=$(echo $ARTIFACTS_INFO | jq -c '. += ["'$ARTIFACT_NAME' (ãƒ“ãƒ«ãƒ‰ã•ã‚ŒãŸ*.nodeãƒ•ã‚¡ã‚¤ãƒ«ã‚’å«ã‚€)"]')" >> $GITHUB_ENV

    - name: ã‚µãƒžãƒªãƒ¼å‡ºåŠ›
      shell: bash
      run: |
        echo "## ðŸ“‹ Build Native Module (${{ inputs.name }}) ã‚µãƒžãƒªãƒ¼" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### ðŸ“Š å®Ÿè¡Œæƒ…å ±" >> $GITHUB_STEP_SUMMARY
        echo "- **ã‚¿ãƒ¼ã‚²ãƒƒãƒˆ:** ${{ inputs.target }}" >> $GITHUB_STEP_SUMMARY
        echo "- **OS:** ${{ inputs.os }}" >> $GITHUB_STEP_SUMMARY
        echo "- **ã‚¢ãƒ¼ã‚­ãƒ†ã‚¯ãƒãƒ£:** ${{ inputs.arch }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        echo "### ðŸ”§ å®Ÿè¡Œã—ãŸã‚¢ã‚¯ã‚·ãƒ§ãƒ³" >> $GITHUB_STEP_SUMMARY
        for action in $(echo $ACTION_SUMMARY | jq -r '.[]'); do
          echo "- $action" >> $GITHUB_STEP_SUMMARY
        done
        echo "" >> $GITHUB_STEP_SUMMARY
        
        echo "### ðŸ“¦ ç”Ÿæˆã•ã‚ŒãŸæˆæžœç‰©" >> $GITHUB_STEP_SUMMARY
        for artifact in $(echo $ARTIFACTS_INFO | jq -r '.[]'); do
          echo "- $artifact" >> $GITHUB_STEP_SUMMARY
        done
        echo "" >> $GITHUB_STEP_SUMMARY
        
        echo "### ðŸ” ãƒ“ãƒ«ãƒ‰ã•ã‚ŒãŸãƒ•ã‚¡ã‚¤ãƒ«" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        echo "$BUILT_FILES" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY 