name: 'Node.jsè¨­å®š'
description: 'Node.jsã®ã‚»ãƒƒãƒˆã‚¢ãƒƒãƒ—ã¨ä¾å­˜é–¢ä¿‚ã®ã‚¤ãƒ³ã‚¹ãƒˆãƒ¼ãƒ«'

inputs:
  node-version:
    description: 'Node.jsã®ãƒãƒ¼ã‚¸ãƒ§ãƒ³ (ç©ºã®å ´åˆã¯.node-versionã‚’ä½¿ç”¨)'
    required: false
    default: ''
  registry-url:
    description: 'npmãƒ¬ã‚¸ã‚¹ãƒˆãƒªã®URL'
    required: false
    default: 'https://registry.npmjs.org'
  package-path:
    description: 'ãƒ‘ãƒƒã‚±ãƒ¼ã‚¸ã®ãƒ‘ã‚¹'
    required: false
    default: '.'

runs:
  using: "composite"
  steps:
    - name: å®Ÿè¡Œæƒ…å ±ã®åˆæœŸåŒ–
      shell: bash
      run: |
        echo "ACTION_SUMMARY=[]" >> $GITHUB_ENV
        echo "INSTALLED_TOOLS=[]" >> $GITHUB_ENV

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: ${{ inputs.node-version == '' && '.node-version' || '' }}
        node-version: ${{ inputs.node-version != '' && inputs.node-version || '' }}
        registry-url: ${{ inputs.registry-url }}
    
    - name: Node.jsæƒ…å ±è¨˜éŒ²
      shell: bash
      run: |
        NODE_VERSION=$(node -v)
        NPM_VERSION=$(npm -v)
        echo "INSTALLED_TOOLS=$(echo $INSTALLED_TOOLS | jq -c '. += ["Node.js (ãƒãƒ¼ã‚¸ãƒ§ãƒ³: '$NODE_VERSION')"]')" >> $GITHUB_ENV
        echo "INSTALLED_TOOLS=$(echo $INSTALLED_TOOLS | jq -c '. += ["npm (ãƒãƒ¼ã‚¸ãƒ§ãƒ³: '$NPM_VERSION')"]')" >> $GITHUB_ENV
        echo "ACTION_SUMMARY=$(echo $ACTION_SUMMARY | jq -c '. += ["Node.js '$NODE_VERSION' ã‚’ã‚»ãƒƒãƒˆã‚¢ãƒƒãƒ—ã—ã¾ã—ãŸ"]')" >> $GITHUB_ENV
    
    - name: add antfu/ni
      shell: bash
      run: |
        npm i -g @antfu/ni
        echo "INSTALLED_TOOLS=$(echo $INSTALLED_TOOLS | jq -c '. += ["@antfu/ni (npm ã‚¯ãƒ©ã‚¤ã‚¢ãƒ³ãƒˆ)"]')" >> $GITHUB_ENV
        echo "ACTION_SUMMARY=$(echo $ACTION_SUMMARY | jq -c '. += ["@antfu/ni ãƒ„ãƒ¼ãƒ«ã‚’ã‚¤ãƒ³ã‚¹ãƒˆãƒ¼ãƒ«ã—ã¾ã—ãŸ"]')" >> $GITHUB_ENV

    - name: ä¾å­˜é–¢ä¿‚ã‚¤ãƒ³ã‚¹ãƒˆãƒ¼ãƒ«
      shell: bash
      working-directory: ${{ inputs.package-path }}
      run: |
        nci
        echo "ACTION_SUMMARY=$(echo $ACTION_SUMMARY | jq -c '. += ["ãƒ‘ãƒƒã‚±ãƒ¼ã‚¸ä¾å­˜é–¢ä¿‚ã‚’ '${{ inputs.package-path }}' ã«ã‚¤ãƒ³ã‚¹ãƒˆãƒ¼ãƒ«ã—ã¾ã—ãŸ"]')" >> $GITHUB_ENV

    - name: ã‚µãƒžãƒªãƒ¼å‡ºåŠ›
      shell: bash
      run: |
        echo "## ðŸ“¦ Node.jsè¨­å®š ã‚µãƒžãƒªãƒ¼" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### ðŸ“Š å®Ÿè¡Œæƒ…å ±" >> $GITHUB_STEP_SUMMARY
        echo "- **Node.jsãƒãƒ¼ã‚¸ãƒ§ãƒ³è¨­å®š:** ${{ inputs.node-version == '' && '.node-versionãƒ•ã‚¡ã‚¤ãƒ«ã‹ã‚‰' || inputs.node-version }}" >> $GITHUB_STEP_SUMMARY
        echo "- **npmãƒ¬ã‚¸ã‚¹ãƒˆãƒªURL:** ${{ inputs.registry-url }}" >> $GITHUB_STEP_SUMMARY
        echo "- **ãƒ‘ãƒƒã‚±ãƒ¼ã‚¸ãƒ‘ã‚¹:** ${{ inputs.package-path }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        echo "### ðŸ”§ å®Ÿè¡Œã—ãŸã‚¢ã‚¯ã‚·ãƒ§ãƒ³" >> $GITHUB_STEP_SUMMARY
        for action in $(echo $ACTION_SUMMARY | jq -r '.[]'); do
          echo "- $action" >> $GITHUB_STEP_SUMMARY
        done
        echo "" >> $GITHUB_STEP_SUMMARY
        
        echo "### ðŸ› ï¸ ã‚¤ãƒ³ã‚¹ãƒˆãƒ¼ãƒ«ã•ã‚ŒãŸãƒ„ãƒ¼ãƒ«" >> $GITHUB_STEP_SUMMARY
        for tool in $(echo $INSTALLED_TOOLS | jq -r '.[]'); do
          echo "- $tool" >> $GITHUB_STEP_SUMMARY
        done
